import { Link, useParams } from 'react-router-dom'
import { ChevronLeft, Minus, Plus, ShoppingBag, Star } from 'lucide-react'
import { useData } from '../context/DataContext'
import { useRevealAnimation } from '../hooks/useRevealAnimation'
import { Button } from '../components/ui'
import { foodImage } from '../utils/foodImages'

export default function ProductPage() {
  const { id } = useParams(); const { menu, cart, addToCart, updateCartQty } = useData(); const product = menu.find((item) => item.id === id); const pageRef = useRevealAnimation(!!product)
  if (!product) return <div className="mx-auto max-w-4xl px-4 py-24 text-center"><p className="text-5xl">🍔</p><h1 className="mt-5 text-3xl font-black">Item not found</h1><Link to="/menu" className="mt-6 inline-block"><Button className="rounded-full">Back to menu</Button></Link></div>
  const inCart = cart.find((item) => item.id === product.id)
  return <div ref={pageRef} className="mx-auto max-w-5xl px-4 py-12"><Link to="/menu" className="inline-flex items-center gap-1 text-sm font-bold text-stone-600 hover:text-brand-600"><ChevronLeft className="h-4 w-4" />Back to menu</Link><div className="mt-6 grid gap-10 lg:grid-cols-2"><div data-gsap-in="slide-left"><img src={foodImage(product)} alt={product.name} className="aspect-square w-full rounded-[2.5rem] object-cover shadow-sm" /></div><div data-gsap-in="slide-right" className="py-4"><div className="flex items-center gap-2 text-sm font-bold text-brand-600">{product.popular && <><Star className="h-4 w-4" fill="currentColor" />Customer favourite</>}{!product.popular && product.category}</div><h1 className="mt-3 text-4xl font-black tracking-tight text-surface-900 sm:text-5xl">{product.name}</h1><p className="mt-5 text-lg leading-8 text-stone-600">{product.description}</p><p className="mt-7 text-3xl font-black text-brand-600">${Number(product.price).toFixed(2)}</p><div className="mt-8 flex flex-wrap gap-3">{inCart ? <div className="flex items-center gap-4 rounded-full bg-surface-900 px-3 py-2 text-white"><button onClick={() => updateCartQty(product.id, inCart.qty - 1)}><Minus className="h-5 w-5" /></button><span className="min-w-5 text-center font-bold">{inCart.qty}</span><button onClick={() => updateCartQty(product.id, inCart.qty + 1)}><Plus className="h-5 w-5" /></button></div> : <Button size="lg" className="rounded-full px-7" onClick={() => addToCart(product)}><Plus className="h-5 w-5" />Add to order</Button>}<Link to="/checkout"><Button size="lg" variant="secondary" className="rounded-full px-7"><ShoppingBag className="h-5 w-5" />View order</Button></Link></div><div className="mt-10 border-t border-[#eadfd2] pt-6 text-sm leading-6 text-stone-500"><p className="font-bold text-surface-900">Good to know</p><p className="mt-1">Made fresh after you order. Let us know about any allergies when you collect your meal.</p></div></div></div></div>
}
