-- Adds a varied, client-ready menu. Safe to run more than once: existing names are skipped.
with products(name, category, price, description, popular) as (
  values
    ('Classic Smash Burger','Burgers',8.99,'Two smashed beef patties, cheddar, pickles and house sauce.',true),
    ('Double Cheese Smash','Burgers',10.99,'Double beef, double cheese, onions and burger sauce.',true),
    ('Bacon BBQ Burger','Burgers',10.49,'Beef patty, smoky bacon, cheddar and barbecue glaze.',false),
    ('Mushroom Swiss Burger','Burgers',9.99,'Beef patty, sautéed mushrooms and Swiss cheese.',false),
    ('Jalapeño Heat Burger','Burgers',9.99,'Beef, pepper jack, jalapeños and spicy mayo.',true),
    ('Truffle House Burger','Burgers',11.49,'Beef, truffle aioli, caramelized onion and rocket.',false),
    ('Crispy Fish Burger','Burgers',8.99,'Golden fish fillet, slaw and tangy tartar sauce.',false),
    ('Veggie Garden Burger','Burgers',8.49,'Plant-based patty, avocado, tomato and crisp lettuce.',false),
    ('Mini Slider Trio','Burgers',9.49,'Three mini cheeseburgers with pickles and onions.',false),
    ('The Big House Burger','Burgers',12.99,'Three patties, cheddar, lettuce, pickles and house sauce.',true),
    ('Crispy Chicken Classic','Chicken',8.49,'Crispy chicken breast, lettuce, pickles and mayo.',true),
    ('Hot Honey Chicken Burger','Chicken',9.49,'Crispy chicken, hot honey glaze and cool slaw.',true),
    ('Nashville Chicken Burger','Chicken',9.49,'Spiced fried chicken, pickles and creamy sauce.',false),
    ('Grilled Chicken Burger','Chicken',8.99,'Flame-grilled chicken, tomato, lettuce and herb mayo.',false),
    ('Chicken Tenders 3pc','Chicken',6.99,'Three hand-breaded chicken tenders with dip.',false),
    ('Chicken Tenders 5pc','Chicken',9.49,'Five hand-breaded chicken tenders with dip.',true),
    ('Spicy Wings 6pc','Chicken',7.99,'Six juicy wings tossed in signature hot glaze.',true),
    ('BBQ Wings 6pc','Chicken',7.99,'Six crispy wings in smoky barbecue sauce.',false),
    ('Garlic Parmesan Wings','Chicken',8.49,'Six wings with garlic butter and parmesan.',false),
    ('Chicken Popcorn Bowl','Chicken',6.49,'Crispy chicken bites with fries and a sauce pot.',false),
    ('Crispy Chicken Wrap','Wraps',7.49,'Crispy chicken, salad, tomato and ranch dressing.',true),
    ('Spicy Chicken Wrap','Wraps',7.99,'Crispy chicken, jalapeños, slaw and spicy mayo.',false),
    ('Grilled Chicken Wrap','Wraps',7.99,'Grilled chicken, avocado, greens and herb dressing.',false),
    ('Beef Shawarma Wrap','Wraps',8.49,'Seasoned beef, onion, lettuce and garlic sauce.',true),
    ('Falafel Tahini Wrap','Wraps',6.99,'Crispy falafel, salad, pickles and tahini sauce.',false),
    ('Halloumi Veggie Wrap','Wraps',7.49,'Grilled halloumi, roasted vegetables and pesto.',false),
    ('Buffalo Chicken Wrap','Wraps',7.99,'Chicken tenders, buffalo sauce and blue cheese slaw.',false),
    ('Caesar Chicken Wrap','Wraps',7.99,'Grilled chicken, parmesan, romaine and Caesar dressing.',false),
    ('Loaded Fries Wrap','Wraps',7.49,'Seasoned fries, cheese sauce, jalapeños and salsa.',false),
    ('Breakfast Egg Wrap','Wraps',6.99,'Egg, cheese, hash browns and tomato relish.',false),
    ('Margherita Pizza','Pizza',9.99,'Tomato sauce, mozzarella, basil and olive oil.',true),
    ('Pepperoni Pizza','Pizza',11.49,'Tomato sauce, mozzarella and pepperoni slices.',true),
    ('BBQ Chicken Pizza','Pizza',11.99,'Chicken, barbecue sauce, onion and mozzarella.',false),
    ('Spicy Beef Pizza','Pizza',11.99,'Seasoned beef, jalapeños, onions and chili flakes.',false),
    ('Four Cheese Pizza','Pizza',10.99,'Mozzarella, cheddar, parmesan and blue cheese.',false),
    ('Veggie Supreme Pizza','Pizza',10.99,'Peppers, onion, mushrooms, olives and mozzarella.',false),
    ('Chicken Alfredo Pizza','Pizza',11.99,'Creamy sauce, chicken, spinach and parmesan.',false),
    ('Meat Feast Pizza','Pizza',12.99,'Pepperoni, beef, chicken and smoky sausage.',true),
    ('Pesto Chicken Pizza','Pizza',11.99,'Basil pesto, chicken, mozzarella and cherry tomatoes.',false),
    ('Garlic Bread Pizza','Pizza',7.49,'Cheesy garlic bread with herb butter and mozzarella.',false),
    ('Salted Fries','Sides',2.99,'Golden fries finished with sea salt.',true),
    ('Loaded Fries','Sides',4.99,'Fries, cheese sauce, jalapeños and house seasoning.',true),
    ('Chili Cheese Fries','Sides',5.49,'Crispy fries with beef chili and melted cheese.',false),
    ('Curly Fries','Sides',3.99,'Seasoned curly fries with a crunchy bite.',false),
    ('Onion Rings','Sides',3.99,'Beer-battered onion rings with smoky dip.',false),
    ('Mozzarella Sticks','Sides',5.49,'Six golden mozzarella sticks with tomato dip.',false),
    ('Mac and Cheese Bites','Sides',5.99,'Crispy bites filled with creamy macaroni cheese.',false),
    ('Chicken Loaded Nachos','Sides',6.99,'Corn chips, chicken, cheese, salsa and jalapeños.',false),
    ('Coleslaw Cup','Sides',2.49,'Fresh and creamy house-made coleslaw.',false),
    ('Side Garden Salad','Sides',3.49,'Leaves, cucumber, tomato and citrus dressing.',false),
    ('Chocolate Milkshake','Shakes',3.99,'Rich chocolate shake with whipped cream.',true),
    ('Vanilla Bean Shake','Shakes',3.99,'Classic vanilla shake with a creamy finish.',false),
    ('Strawberry Shake','Shakes',3.99,'Sweet strawberry shake, blended thick.',false),
    ('Cookies and Cream Shake','Shakes',4.49,'Vanilla shake blended with chocolate cookies.',true),
    ('Salted Caramel Shake','Shakes',4.49,'Caramel shake with a hint of sea salt.',false),
    ('Peanut Butter Shake','Shakes',4.49,'Smooth peanut butter blended into vanilla ice cream.',false),
    ('Mango Lassi Shake','Shakes',3.99,'Mango, yoghurt and a touch of cardamom.',false),
    ('Banana Date Shake','Shakes',3.99,'Banana, dates and cold milk, blended smooth.',false),
    ('Mocha Frappe','Shakes',4.49,'Iced coffee, chocolate and whipped cream.',false),
    ('Oreo Brownie Shake','Shakes',4.99,'Cookies, brownie pieces and vanilla ice cream.',true),
    ('Cola','Drinks',1.99,'Ice-cold classic cola.',false),
    ('Diet Cola','Drinks',1.99,'Sugar-free sparkling cola.',false),
    ('Lemon Lime Soda','Drinks',1.99,'Crisp lemon-lime sparkling drink.',false),
    ('Orange Soda','Drinks',1.99,'Bright orange sparkling drink.',false),
    ('Sparkling Water','Drinks',1.49,'Chilled sparkling mineral water.',false),
    ('Still Water','Drinks',1.29,'Chilled bottled water.',false),
    ('Fresh Lemonade','Drinks',2.99,'Fresh lemon, mint and sparkling water.',true),
    ('Peach Iced Tea','Drinks',2.99,'Black tea with peach and fresh ice.',false),
    ('Iced Latte','Drinks',3.49,'Fresh espresso over ice with cold milk.',false),
    ('Cold Brew Coffee','Drinks',3.99,'Slow-steeped cold brew over ice.',false),
    ('Classic Burger Meal','Meals',11.99,'Classic smash burger, salted fries and a cola.',true),
    ('Double Cheese Meal','Meals',13.99,'Double cheese smash, fries and a cola.',true),
    ('Crispy Chicken Meal','Meals',11.49,'Crispy chicken burger, fries and a cola.',false),
    ('Spicy Chicken Meal','Meals',12.49,'Hot honey chicken burger, fries and a cola.',false),
    ('Tender Box Meal','Meals',12.99,'Five tenders, fries, coleslaw and a drink.',false),
    ('Wing Box Meal','Meals',13.49,'Six wings, loaded fries and a drink.',false),
    ('Veggie Meal','Meals',10.99,'Veggie garden burger, fries and lemonade.',false),
    ('Wrap Meal','Meals',10.99,'Crispy chicken wrap, fries and a cola.',false),
    ('Pizza Meal for One','Meals',12.99,'Personal pepperoni pizza, side and a drink.',false),
    ('Family Feast','Meals',29.99,'Four burgers, two large fries, wings and four drinks.',true),
    ('Chocolate Brownie','Desserts',3.49,'Warm chocolate brownie with a fudgy centre.',true),
    ('Salted Caramel Brownie','Desserts',3.99,'Chocolate brownie topped with salted caramel.',false),
    ('New York Cheesecake','Desserts',4.49,'Creamy baked cheesecake with berry sauce.',false),
    ('Cookie Dough Skillet','Desserts',4.99,'Warm cookie dough with vanilla ice cream.',true),
    ('Chocolate Chip Cookie','Desserts',1.99,'Soft-centre cookie with dark chocolate chunks.',false),
    ('Churros','Desserts',3.99,'Cinnamon sugar churros with chocolate dip.',false),
    ('Apple Pie Pocket','Desserts',2.99,'Warm apple pie pastry with cinnamon sugar.',false),
    ('Vanilla Sundae','Desserts',2.99,'Vanilla ice cream with chocolate sauce.',false),
    ('Chocolate Sundae','Desserts',2.99,'Chocolate ice cream with fudge sauce.',false),
    ('Strawberry Sundae','Desserts',2.99,'Vanilla ice cream with strawberry sauce.',false),
    ('Kids Cheeseburger','Kids',5.99,'Small cheeseburger, fries and apple juice.',false),
    ('Kids Chicken Bites','Kids',5.99,'Chicken bites, fries and apple juice.',false),
    ('Kids Mini Wrap','Kids',5.99,'Small chicken wrap, fries and apple juice.',false),
    ('Kids Mac and Cheese','Kids',5.49,'Creamy macaroni cheese with fruit cup.',false),
    ('Kids Pizza Slice','Kids',5.49,'Cheese pizza slice, fries and apple juice.',false),
    ('Kids Fish Bites','Kids',5.99,'Crispy fish bites, fries and apple juice.',false),
    ('Breakfast Burger','Breakfast',6.99,'Egg, beef patty, cheese and hash brown.',false),
    ('Egg and Cheese Muffin','Breakfast',4.49,'Soft muffin with egg, cheddar and herb mayo.',false),
    ('Chicken Breakfast Muffin','Breakfast',5.49,'Crispy chicken, egg and cheese in a muffin.',false),
    ('Pancake Stack','Breakfast',5.99,'Three fluffy pancakes with maple syrup.',false)
)
insert into public.menu_items (name, category, price, description, image, popular)
select name, category, price, description, '🍽️', popular
from products p
where not exists (select 1 from public.menu_items m where lower(m.name) = lower(p.name));
